import { Header } from "@/components/header/Header";
import { Inicio } from "./inicio/Inicio";
import { Servicos } from "@/components/services/Servicos";

import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";

const mainFontFamily = Roboto({
  weight: ["100", "300", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="h-[100vh] flex flex-col justify-between items-center bg-[#fff]">
      <Header />
      <Inicio />
      {/* <Servicos /> */}
      {/* <Carousel /> */}
      {/* <ClientsCarousel /> */}
    </main>
  );
}
